version: "3"

services:
  minecraft:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
    ports:
      - "25565:25565"
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - /home/harald/minecraft:/data